name: Databricks Checkout
description: Push a branch to Databricks Repos. If the repo doesn't exist, create it first.

inputs:
  host:
    description: Databricks Host (should begin with https://)
    required: true
  token:
    description: Databricks API token
    required: true
  recursive:
    description: Whether copy action should be executed recursively
    default: true
    type: boolean
  overwrite:
    description: Whether to overwrite files
    default: true
    type: boolean
  source:
    description: Local file/directory to copy over
    default: '${GITHUB_WORKSPACE}'
  destination:
    description: Path on DBFS, needs to start with `/`
    default: '/${GITHUB_REPOSITORY}'

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: |
        python -m pip install --upgrade pip wheel
        python -m pip install -r "${GITHUB_ACTION_PATH}/requirements.txt"
      shell: bash
    - run: |
        python "${GITHUB_ACTION_PATH}/dbfs.py" \
          --host ${{ inputs.host }} \
          --token ${{ inputs.token }} \
          --recursive ${{ inputs.recursive }} \
          --overwrite ${{ inputs.overwrite }} \
          --source "${{ inputs.source }}" \
          --destination "${{ inputs.destination }}"
      shell: bash
