name: Databricks Jobs Run Now
description: Trigger a new job run

inputs:
  host:
    description: Databricks host
    required: true
  token:
    description: Databricks API token
    required: true
  job-id:
    description: Job Id
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: |
        python -m pip install --upgrade pip wheel
        python -m pip install -r "${GITHUB_ACTION_PATH}/requirements.txt"
      shell: bash
    - run: |
        python "${GITHUB_ACTION_PATH}/run_now.py" \
          --host ${{ inputs.host }} \
          --token ${{ inputs.token }} \
          --job-id ${{ inputs.job-id }}
      shell: bash
