name: Databricks Dbt Job Create 
description: Create a new dbt job on Databricks

inputs:
  host:
    description: Databricks host
    required: true
  token:
    description: Databricks API token
    required: true
  project-directory:
    description: Project DBFS path on Databricks
    required: true
  target:
    description: Target environment
    required: true
  operation:
    description: dbt operation command type
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: |
        python -m pip install --upgrade pip wheel
        python -m pip install -r "${GITHUB_ACTION_PATH}/requirements.txt"
      shell: bash
    - run: |
        python "${GITHUB_ACTION_PATH}/checkout.py" \
          --url "https://github.com/${GITHUB_REPOSITORY}" \
          --branch "${GITHUB_REF}" \
          --host ${{ inputs.host }} \
          --token ${{ inputs.token }} \
          --project-directory ${{ inputs.project-directory }}
          --target ${{ inputs.target }}
          --operation ${{ inputs.operation }}
      shell: bash
