name: Databricks Workflow
on: push
jobs:
  databricks:
    name: Sync Repository
    runs-on: ubuntu-latest
    steps:
      - name: Databricks Checkout
        uses: ./.databricks/actions/checkout
        with:
            host: ${{ secrets.DATABRICKS_HOST }}
            token: ${{ secrets.DATABRICKS_TOKEN }}
            path: /Repos/{user}/{folder}
